# Generated by Django 3.1.4 on 2020-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='required_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(max_length=50),
        ),
    ]
